Client:
  type: entity
  table: clients
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    nom:
      type: string

    prenom:
      type: string
  
    sexe:
      type: string
  
    adresse:
      type: string
  
    ville:
      type: string
  
    codepostal:
      type: string
  
    email:
      type: string
  
    login:
      type: string
  
    telephone:
      type: string
  
    password:
      type: string